#!/bin/sh

. ./prepare

PKGNAME=dropmonitor

DIST1=.el6_3.12.6_iso_v1.0
DIST2=.el6_3.12.6_iso_v1.3
DIST3=.el6_3.12.6_iso_v1.8
DIST4=.el6_han_3.12.6
DIST5=.el6_3.12.6_iso_v2.1
DIST6=.el6_3.12.6_iso_v2.2
DIST=${DIST5}

# release number
RELEASE=1

VER=1.0 # 

echo ' Cleanning old source...'

rm -fr $BUILDROOT/root/rpmbuild/BUILD/${PKGNAME}*

echo ' Preparing source...'

cp -r --preserve=links $SOURCEDIR/${PKGNAME} $BUILDROOT/root/rpmbuild/BUILD/${PKGNAME}-${VER}
cp utils/${PKGNAME}.spec $BUILDROOT/root/rpmbuild/SPECS/${PKGNAME}.spec

for src in dummy 
do
    cp utils/$src $BUILDROOT/root/rpmbuild/SOURCES/
done

echo " Building ${PKGNAME}......"

chroot $BUILDROOT rpmbuild -ba -D"Ver ${VER}" -D"rel ${RELEASE}" -D"dist ${DIST}" -D"name ${PKGNAME}" /root/rpmbuild/SPECS/${PKGNAME}.spec

#rpmbuild -bb /root/rpmbuild/SPECS/${PKGNAME}.spec

. ./finish

mount -l |grep buildroot
if [ "$?" = '0' ]; then
    echo Warning, Some bind dir couldn\'t not be umounted, look by mount -l 
fi 
echo ' Finished!'



